config/routes.rb
Hrms::Application.routes.draw do

   root :to => 'session#index'
   resources:session do
    collection do
     get 'authenticate'
     post 'authenticate'
     get 'logout'

   end
   end
   resources:user do
    collection do
      get 'add_role'
      post 'role'
      get 'new_user'
      post 'add_user'
      get 'education'
      post 'education'
      get 'edit_photo'
      post 'save_photo'
    end
  end
  resources:employee do
    collection do
      get 'hr'
      post 'hr'
      get 'manager'
      post 'manager'
      get 'employee'
      post 'employee'

    end
  end
  resources :userprof do
    collection do
    end
  end

end

app/models/certificate.rb
class Certificate < ActiveRecord::Base
  attr_accessible :employee_id, :certificate_name, :certificate_provider
  belongs_to :employee
end

app/models/education.rb
class Education < ActiveRecord::Base
   attr_accessible :employee_id, :course_name, :course_institution, :course_percentage, :year_of_passing
   belongs_to :employee
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :user_id, :name, :age, :gender, :address, :phone_number, :email_id, :date_of_joining, :manager_id
  belongs_to :user
  has_one :employee_image
  has_many :educations
  has_many :certificates
  has_many :skills
  has_many :subordinates, :class_name => "Employee", :foreign_key => "manager_id"
  belongs_to :manager, :class_name =>"Employee"

end

app/models/employee_image.rb
class EmployeeImage < ActiveRecord::Base
   attr_accessible :employee_id, :photo_name, :profimage, :remote_profimage_url
   belongs_to :employee
   mount_uploader :profimage, ProfimageUploader
end

app/models/role.rb
class Role < ActiveRecord::Base
   attr_accessible :role_name
   has_many :users, :through => :role_user
   has_one :role_user
end

app/models/role_user.rb
class RoleUser < ActiveRecord::Base
  attr_accessible :user_id, :role_id
  belongs_to :user
  belongs_to :role
end

app/models/skill.rb
class Skill < ActiveRecord::Base
   attr_accessible :employee_id, :skill_name, :notes
   belongs_to :employee
end

app/models/user.rb
class User < ActiveRecord::Base
   attr_accessible :user_name, :password
   has_one :role, :through => :role_user
   has_one :employee
   has_one :role_user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController

  # list out the employees in the index page
  def index
    @user=User.order("user_name").page(params[:page]).per(1)
    @search = Employee.search(params[:q])
    @use = @search.result
    @user = @use.order("id").page(params[:page]).per(2)
  end

  #list out the hr's in the user's list
  def hr
  	@user=User.all
  end

  #list out the managers in the user's list
  def manager
  @user=User.find(session['user_id'])
  @employee=@user.employee.subordinates
  end

  #list out the employees(common users)
  def employee
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	def index
	end
	
	def authenticate
		user_name =  params['session']['user_name']
		password =  params['session']['password']
		@user = User.find_by_user_name(user_name)
		
		if @user
			if @user.password == password
				session['user_id'] = @user.id
				if @user.role.role_name == 'admin'
					redirect_to employee_index_path and return 
				end	
				if @user.role.role_name == 'hr'
					redirect_to  hr_employee_index_path and return
				end	
				if @user.role.role_name == 'manager'
					redirect_to  manager_employee_index_path and return
				end	
				if @user.role.role_name == 'employee'
					redirect_to   employee_employee_index_path and return
				end
			else
				redirect_to root_path, :notice => "Incorrect user name or password " and return
			end
		
		else
			flash[:notice] = "No such user exist, Please register to continue "
			redirect_to root_path and return
		end
	
	end

	def logout
		reset_session
		redirect_to session_index_path and return
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def index
  end

  def add_role
  	@role=Role.new
  end

  def role
	 @role=Role.new(params[:role])
  	if @role.save
		  redirect_to employee_index_path, :notice =>"The new role is created"
    else
      render "add_role"
    end
  end

  def new_user
    @user=User.new
  end

  def add_user
    @user = User.new(params[:user])
    @employee=@user.build_employee(params[:employee])
    @role=@user.build_role_user(:role_id => 4)
    if @user.save
      @user.employee.create_employee_image(params[:p])
      @user.employee.educations.create(params[:education])
      @user.employee.skills.create(params[:skill])
      @user.employee.certificates.create(params[:certificate])
      redirect_to hr_employee_index_path and return
    else 
      render "new_user" 
    end
  end  

  def edit_photo
    @employee=Employee.find(session['user_id'])
    @employee_image=EmployeeImage.new
  end

  def save_photo
    @employee=Employee.find(session['user_id'])  
    @employee.create_employee_image(params[:employee_image])
    redirect_to user_path(session['user_id'])   
  end

	def show
    @employee=Employee.find(params[:id])
    @education=@employee.educations
    @certificate=@employee.certificates
    @role=@employee.user.role
  end

  def edit
    @user=User.find(params[:id])
    @employee = @user.employee
    @role_user=@user.role_user
  end 

  def update
    @user=User.find(params[:id])
    @employee = @user.employee
    @role_user=@user.role_user
      if @employee.update_attributes(params[:employee])
        if @role_user.update_attributes(params[:role_user])
          redirect_to userprof_path(:education)
        end
      else 
        render "edit"
      end

  end

  def education
    @education=Education.find(@employee)
    if @education.update_attributes(params[:education])

      redirect_to user_path(session['user_id'])
    end
  end
end

app/controllers/userprof_controller.rb
class UserprofController < Wicked::WizardController

steps :education, :certificate, :skill

  def show
  	user = User.find(session[:user_id])
  	@employee = user.employee
    @education = @employee.educations
    @certificate = @employee.certificates
    @skills = @employee.skills
  	render_wizard
  end

  def edit
  	user = User.find(session[:user_id])
    @employee = user.employee
  end

  def update	
    user = User.find(session[:user_id])
    @employee = user.employee
    case step
    	when :education
    		@employee.update_attributes(params[:education])
    	
   		when :certificate
    		@employee.update_attributes(params[:certificate])
    
    	when :skill
    		@employee.update_attributes(params[:skill])
    	
  	end
  	render_wizard
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/userprof_helper.rb
module UserprofHelper
end

app/views/employee/employee.html.erb
<%= image_tag("1.jpg", :alt => "test image" ,:style =>"width:200px;")%>
	<h1> welcome to your account <h1>
		<%= link_to 'home', employee_employee_index_path %>
		<%= link_to 'show',user_path(session['user_id'])  %>
		<%= link_to 'logout',logout_session_index_path %>
		<%= link_to 'editphoto', edit_photo_user_index_path %>

app/views/employee/hr.html.erb
<%= image_tag("hr.jpeg", :alt => "test image" ,:style =>"width:200px;")%>
	<h1> welcome to your account <h1>
	<%= link_to 'home', hr_employee_index_path %>
	<%= link_to 'show',user_path(session['user_id'])  %>
	<%= link_to 'add user' ,new_user_user_index_path%>
	<%= link_to 'logout',logout_session_index_path %><br></br>
	<% @user.each do |f| %>
		<% if f.role.role_name != 'admin' %>
			<% if f.role.role_name != 'hr' %>
			<%= link_to f.employee.name, user_path(f) %>
			<% end %>
		<% end %>
	<% end %>

	<%= link_to 'editphoto', edit_photo_user_index_path %>

app/views/employee/index.html.erb
<%= image_tag("images.jpeg", :alt => "test image" ,:style =>"width:200px;")%>

<%= search_form_for @search, url: employee_index_path  do |f| %>
<%= f.label :name_cont, "username Contain" %>
<%= f.text_field :name_cont %>
<%= f.submit 'search' %>
<%end %>

<h1> welcome to your account <h1>
	<%= link_to 'home',employee_index_path %>
	<%= link_to 'AddRole', add_role_user_index_path %>
	<%= link_to 'show',user_path(session['user_id']) %>
	<%= link_to 'logout', logout_session_index_path %><br></br>
	<%= paginate @user, :window => 3 %>
	<% @user.each do |f| %>
		<% if f.user.role.role_name != 'admin' %>
			<%= link_to f.name, user_path(f) %>
		<% end %>
	<% end %><br /><br />
	<%= link_to 'editphoto', edit_photo_user_index_path %>

app/views/employee/manager.html.erb
<h1>welcome manager</h1>
<%= image_tag("manager.jpg", :alt => "test image" ,:style =>"width:200px;")%>
	<h1> welcome to your account <h1>
	<%= link_to 'home', manager_employee_index_path %>
	<%= link_to 'show', user_path(session['user_id']) %>
	<%= link_to 'logout',logout_session_index_path %><br /><br />
	<% @employee.each do |f| %>
		<%= link_to f.name, user_path(f) %>
	<% end %>
	<%= link_to 'editphoto', edit_photo_user_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hrms</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/session/index.html.erb
<h1>welcome to the HR management system</h1>

<%= form_for :session, :url => {:action => 'authenticate'} do |f| %>
<div align="right"><%=f.label :user_name %>
<%=f.text_field :user_name %><br></br>

<%=f.label :password %>
<%=f.password_field :password %><br></br>

<%=f.submit "login" %></div>
<%= image_tag("hrms.gif", :alt => "test image" ,:style =>"width:400px;")%>


<% end %>

app/views/user/add_role.html.erb
<h1>New Role</h1>
<%= form_for :role, :url => {:action => 'role'} do |f| %>
<%=f.label :role_name %>
<%=f.text_field :role_name %><br></br>
<%=f.submit "add" %>
<% end %>

app/views/user/edit.html.erb
<%= form_for @employee , :url => { :action => 'update'} do |f| %>
<h1>Edit Profile</h1>
<%=f.label :name %>
<%=f.text_field :name %><br></br>
<%=f.label :age %>
<%=f.text_field :age %><br></br>
<%=f.label :gender %>
<%=f.text_field :gender %><br></br>

<%=f.label :address %>
<%=f.text_field :address %><br></br>
<%=f.label :phone_number %>
<%=f.text_field :phone_number %><br></br>
<%=f.label :email_id %>
<%=f.text_field :email_id %><br></br>
<%=f.label :date_of_joining %>
<%=f.text_field :date_of_joining %><br></br>
<%= fields_for @role_user do |t| %>				
	<%=t.label :role_name %>
	<%= t.select(:role_id, Role.all.collect {|a| [a.role_name, a.id ]}) %>
<% end %>
<%= link_to "skip", userprof_index_path(session['user_id']) %>

<%=f.submit "next" %>

<% end %>

app/views/user/edit_photo.html.erb
<%= form_for @employee_image, :html => {:multipart => true}, :url => { :action => 'save_photo'} do |f| %>
 <p>
    <%= f.label :photo_name %><br />
    <%= f.text_field :photo_name %>
  </p>
  <p>
    <%= f.file_field :profimage %>
  </p>
  <p>
    <%= f.label :remote_profimage_url, "or image URL" %><br />
    <%= f.text_field :remote_profimage_url %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/user/education.html.erb
<h1>Edit Profile</h1>
<h2>Education</h1>
<%= form_for @education , :url => { :action=>'update'} do |f| %>
<%=f.label :course_name %>
<%=f.text_field :course_name %><br></br>
<%=f.label :course_institution %>
<%=f.text_field :course_institution %><br></br>
<%=f.label :course_percentage %>
<%=f.text_field :course_percentage %><br></br>

<%=f.label :year_of_passing %>
<%=f.text_field :year_of_passing %><br></br>
<%=f.submit "save" %>

<% end %>

app/views/user/new_user.html.erb
<h1>Add new User</h1>
<%= form_for :user, :url => {:action => 'add_user'} do |f| %>
<%=f.label :user_name %>
<%=f.text_field :user_name %><br></br>
<%=f.label :password %>
<%=f.text_field :password %><br></br>
<%=f.submit "send" %>

<% end %>

app/views/user/show.html.erb
<div align="right"><h1><%= link_to 'edit', edit_user_path(params[:id]) %></h1></div>
<%= image_tag @employee.employee_image.profimage_url(:thumb) if @employee.employee_image.profimage? %>
<h1><%= @employee.name %> Profile</h1>
<h3>Role : <%= @role.role_name %></h3>
<h3>Name : <%= @employee.name %></h3>
<h3>Age : <%= @employee.age %></h3>
<h3>Gender : <%= @employee.gender %></h3>
<h3>Address : <%= @employee.address %></h3>
<h3>Phone Number : <%= @employee.phone_number %></h3>
<h3>Email id : <%= @employee.email_id %></h3>
<h3>Date of joining : <%= @employee.date_of_joining %></h3>
<h2>Education</h2>
<% @employee.educations.each do |f| %>
<h3>Course_name : <%=f.course_name %></h3>
<h3>course_institution : <%=f.course_institution %></h3>
<h3>course_percentage : <%=f.course_percentage %></h3>
<h3>year of passing : <%=f.year_of_passing %></h3>
<% end %>

<h2>Certificates</h2>
<% @employee.certificates.each do |f| %>
<h3>Certificate_name : <%=f.certificate_name %></h3>
<h3>Certificate_provider : <%=f.certificate_provider %></h3>
<% end %>
<h1><%= link_to 'back' %></h1>

app/views/userprof/certificate.html.erb
<h1>Edit Profile</h1>
<h2>certificate</h1>
<%= form_for @certificate , url: wizard_path do |f| %>
<%=f.label :certificate_name %>
<%=f.text_field :certificate_name %><br></br>
<%=f.label :certificate_provider %>
<%=f.text_field :certificate_provider %><br></br>
<%= link_to 'skip', next_wizard_path %>
<%=f.submit "finish" %>

<% end %>

app/views/userprof/education.html.erb
<h1>Edit Profile</h1>
<h2>Education</h1>
<%= form_for @education , url: wizard_path do |f| %>
<%=f.label :course_name %>
<%=f.text_field :course_name %><br></br>
<%=f.label :course_institution %>
<%=f.text_field :course_institution %><br></br>
<%=f.label :course_percentage %>
<%=f.text_field :course_percentage %><br></br>

<%=f.label :year_of_passing %>
<%=f.text_field :year_of_passing %><br></br>
<%=f.submit "next" %>
<%= link_to 'skip', next_wizard_path %>
<% end %>

app/views/userprof/skill.html.erb
<h1>Edit Profile</h1>
<h2>skills</h1>
<%= form_for @skills , url: wizard_path do |f| %>
<%=f.label :skill_name %>
<%=f.text_field :skill_name %><br></br>

<%=f.submit "finish" %>

<% end %>